import type { Metadata } from "next";
import "./../globals.css";
import StoreProvider from "@/store/provider";
import ThemeProvider from "@/features/theme/providers/theme-provider";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import { Cairo, Inter } from "next/font/google";
import { dinNext } from "@/fonts";
// const cairo = Cairo({
//   subsets: ["arabic"],
//   variable: "--font-cairo",
//   weight: ["400", "500", "600", "700", "800"],
// });

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const locale = await getLocale();
  const messages = await getMessages();

  const isRTL = locale === "ar";

  return (
    <html
      lang={locale}
      dir={isRTL ? "rtl" : "ltr"}
      suppressHydrationWarning
      className={`${dinNext.variable} ${inter.variable}`}
    >
      <body
        suppressHydrationWarning
        className={`min-h-full flex flex-col ${
          isRTL ? "font-(--font-din-next)" : "font-(--font-inter)"
        }`}
      >
        <StoreProvider>
          <ThemeProvider>
            <NextIntlClientProvider locale={locale} messages={messages}>
              <div className="min-h-screen">{children}</div>
            </NextIntlClientProvider>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
